version: "3"

services:
  mysql:
    image: mysql
    volumes:
      - mysql-volume:/var/lib/mysql
    ports:
      - "0.0.0.0:63306:3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_DATABASE=root"
    command: --character-set-server=utf8 --collation-server=utf8_unicode_ci

volumes:
  mysql-volume: